// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: license/v1/license.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// LicenseStatus enumerates the lifecycle states of a license.
type LicenseStatus int32

const (
	// LICENSE_STATUS_UNSPECIFIED is the zero value and never valid in state.
	LicenseStatus_LICENSE_STATUS_UNSPECIFIED LicenseStatus = 0
	// LICENSE_STATUS_ACTIVE marks a license that is currently valid.
	LicenseStatus_LICENSE_STATUS_ACTIVE LicenseStatus = 1
	// LICENSE_STATUS_REVOKED marks a license that has been revoked.
	LicenseStatus_LICENSE_STATUS_REVOKED LicenseStatus = 2
)

var LicenseStatus_name = map[int32]string{
	0: "LICENSE_STATUS_UNSPECIFIED",
	1: "LICENSE_STATUS_ACTIVE",
	2: "LICENSE_STATUS_REVOKED",
}

var LicenseStatus_value = map[string]int32{
	"LICENSE_STATUS_UNSPECIFIED": 0,
	"LICENSE_STATUS_ACTIVE":      1,
	"LICENSE_STATUS_REVOKED":     2,
}

func (x LicenseStatus) String() string {
	return proto.EnumName(LicenseStatus_name, int32(x))
}

func (LicenseStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_702ee587256d947c, []int{0}
}

// Params defines the parameters for the license module.
type Params struct {
	// owner is the address allowed to grant and revoke access within this
	// module. It is empty until governance sets it, and while empty no grant can
	// be made — the module fails closed.
	//
	// Owning the module confers the right to delegate actions, not the actions
	// themselves: the owner must grant itself "type.create" like anyone else.
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_702ee587256d947c, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

// License represents an issued license instance.
type License struct {
	// id is the auto-incremented identifier, unique chain-wide across all
	// license types. A bare id is a complete handle to a license.
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// type is the LicenseType.id this license was issued from.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// holder is the address that owns this license.
	Holder string `protobuf:"bytes,3,opt,name=holder,proto3" json:"holder,omitempty"`
	// start_date is the date from which the license is valid.
	StartDate string `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	// end_date is the date the license stops being valid. As issued it is the
	// expiry date, with the empty string meaning no expiry; revocation
	// overwrites it with the revocation date (block date).
	EndDate string `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	// status is the license lifecycle state.
	Status LicenseStatus `protobuf:"varint,6,opt,name=status,proto3,enum=license.v1.LicenseStatus" json:"status,omitempty"`
}

func (m *License) Reset()         { *m = License{} }
func (m *License) String() string { return proto.CompactTextString(m) }
func (*License) ProtoMessage()    {}
func (*License) Descriptor() ([]byte, []int) {
	return fileDescriptor_702ee587256d947c, []int{1}
}
func (m *License) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *License) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_License.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *License) XXX_Merge(src proto.Message) {
	xxx_messageInfo_License.Merge(m, src)
}
func (m *License) XXX_Size() int {
	return m.Size()
}
func (m *License) XXX_DiscardUnknown() {
	xxx_messageInfo_License.DiscardUnknown(m)
}

var xxx_messageInfo_License proto.InternalMessageInfo

func (m *License) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *License) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *License) GetHolder() string {
	if m != nil {
		return m.Holder
	}
	return ""
}

func (m *License) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

func (m *License) GetEndDate() string {
	if m != nil {
		return m.EndDate
	}
	return ""
}

func (m *License) GetStatus() LicenseStatus {
	if m != nil {
		return m.Status
	}
	return LicenseStatus_LICENSE_STATUS_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("license.v1.LicenseStatus", LicenseStatus_name, LicenseStatus_value)
	proto.RegisterType((*Params)(nil), "license.v1.Params")
	proto.RegisterType((*License)(nil), "license.v1.License")
}

func init() { proto.RegisterFile("license/v1/license.proto", fileDescriptor_702ee587256d947c) }

var fileDescriptor_702ee587256d947c = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcf, 0x6e, 0xda, 0x40,
	0x10, 0x87, 0xbd, 0x2e, 0x98, 0x32, 0x52, 0x11, 0x5a, 0xb5, 0x95, 0x8d, 0x54, 0x0b, 0x71, 0x42,
	0x95, 0xb0, 0xa1, 0xbd, 0xf4, 0xca, 0x1f, 0x57, 0x72, 0x8b, 0x28, 0xb2, 0x81, 0x43, 0x2f, 0x96,
	0x61, 0xb7, 0x60, 0x15, 0xbc, 0xc8, 0xbb, 0x90, 0xe4, 0x2d, 0xf2, 0x30, 0x79, 0x88, 0x1c, 0x72,
	0x40, 0x39, 0xe5, 0x18, 0xc1, 0x8b, 0x44, 0xac, 0x4d, 0xa2, 0x70, 0xc9, 0x6d, 0x7e, 0xfe, 0x3e,
	0xcf, 0xac, 0x66, 0x40, 0x5f, 0x46, 0x33, 0x1a, 0x73, 0x6a, 0x6f, 0x5b, 0x76, 0x56, 0x5a, 0xeb,
	0x84, 0x09, 0x86, 0xe1, 0x14, 0xb7, 0xad, 0x8a, 0x31, 0x63, 0x7c, 0xc5, 0x78, 0x20, 0x89, 0x9d,
	0x86, 0x54, 0xab, 0xfd, 0x00, 0x6d, 0x18, 0x26, 0xe1, 0x8a, 0x63, 0x0b, 0xf2, 0xec, 0x22, 0xa6,
	0x89, 0x8e, 0xaa, 0xa8, 0x5e, 0xec, 0xe8, 0xf7, 0x37, 0x8d, 0x8f, 0x99, 0xda, 0x26, 0x24, 0xa1,
	0x9c, 0xfb, 0x22, 0x89, 0xe2, 0xb9, 0x97, 0x6a, 0xb5, 0x3b, 0x04, 0x85, 0x7e, 0x3a, 0x03, 0x97,
	0x40, 0x8d, 0x88, 0xfc, 0x31, 0xe7, 0xa9, 0x11, 0xc1, 0x18, 0x72, 0xe2, 0x6a, 0x4d, 0x75, 0xf5,
	0xd8, 0xca, 0x93, 0x35, 0x6e, 0x82, 0xb6, 0x60, 0x4b, 0x42, 0x13, 0xfd, 0xdd, 0x1b, 0x03, 0x32,
	0x0f, 0x7f, 0x01, 0xe0, 0x22, 0x4c, 0x44, 0x40, 0x42, 0x41, 0xf5, 0x9c, 0xec, 0x55, 0x94, 0x5f,
	0x7a, 0xa1, 0xa0, 0xd8, 0x80, 0xf7, 0x34, 0x26, 0x29, 0xcc, 0x4b, 0x58, 0xa0, 0x31, 0x91, 0xa8,
	0x05, 0x1a, 0x17, 0xa1, 0xd8, 0x70, 0x5d, 0xab, 0xa2, 0x7a, 0xe9, 0x9b, 0x61, 0xbd, 0x6c, 0xc3,
	0xca, 0x1e, 0xed, 0x4b, 0xc1, 0xcb, 0xc4, 0xaf, 0xff, 0xe0, 0xc3, 0x2b, 0x80, 0x4d, 0xa8, 0xf4,
	0xdd, 0xae, 0x33, 0xf0, 0x9d, 0xc0, 0x1f, 0xb5, 0x47, 0x63, 0x3f, 0x18, 0x0f, 0xfc, 0xa1, 0xd3,
	0x75, 0x7f, 0xba, 0x4e, 0xaf, 0xac, 0x60, 0x03, 0x3e, 0x9d, 0xf1, 0x76, 0x77, 0xe4, 0x4e, 0x9c,
	0x32, 0xc2, 0x15, 0xf8, 0x7c, 0x86, 0x3c, 0x67, 0xf2, 0xe7, 0xb7, 0xd3, 0x2b, 0xab, 0x9d, 0x5f,
	0xb7, 0x7b, 0x13, 0xed, 0xf6, 0x26, 0x7a, 0xdc, 0x9b, 0xe8, 0xfa, 0x60, 0x2a, 0xbb, 0x83, 0xa9,
	0x3c, 0x1c, 0x4c, 0xe5, 0x6f, 0x73, 0x1e, 0x89, 0xc5, 0x66, 0x6a, 0xcd, 0xd8, 0xca, 0x8e, 0x19,
	0xa1, 0xcb, 0x70, 0xca, 0x1b, 0x9c, 0xfc, 0x7f, 0x0e, 0xf6, 0xe5, 0xe9, 0xc6, 0xf6, 0x71, 0xa3,
	0x7c, 0xaa, 0xc9, 0x1b, 0x7e, 0x7f, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x4a, 0x67, 0xe5, 0x06,
	0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintLicense(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *License) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *License) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *License) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Status != 0 {
		i = encodeVarintLicense(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if len(m.EndDate) > 0 {
		i -= len(m.EndDate)
		copy(dAtA[i:], m.EndDate)
		i = encodeVarintLicense(dAtA, i, uint64(len(m.EndDate)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.StartDate) > 0 {
		i -= len(m.StartDate)
		copy(dAtA[i:], m.StartDate)
		i = encodeVarintLicense(dAtA, i, uint64(len(m.StartDate)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Holder) > 0 {
		i -= len(m.Holder)
		copy(dAtA[i:], m.Holder)
		i = encodeVarintLicense(dAtA, i, uint64(len(m.Holder)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Type) > 0 {
		i -= len(m.Type)
		copy(dAtA[i:], m.Type)
		i = encodeVarintLicense(dAtA, i, uint64(len(m.Type)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintLicense(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintLicense(dAtA []byte, offset int, v uint64) int {
	offset -= sovLicense(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovLicense(uint64(l))
	}
	return n
}

func (m *License) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovLicense(uint64(m.Id))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovLicense(uint64(l))
	}
	l = len(m.Holder)
	if l > 0 {
		n += 1 + l + sovLicense(uint64(l))
	}
	l = len(m.StartDate)
	if l > 0 {
		n += 1 + l + sovLicense(uint64(l))
	}
	l = len(m.EndDate)
	if l > 0 {
		n += 1 + l + sovLicense(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovLicense(uint64(m.Status))
	}
	return n
}

func sovLicense(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLicense(x uint64) (n int) {
	return sovLicense(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLicense
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLicense
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLicense
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLicense(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLicense
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *License) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLicense
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: License: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: License: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLicense
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLicense
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Holder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLicense
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLicense
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Holder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLicense
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLicense
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StartDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndDate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLicense
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLicense
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndDate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= LicenseStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipLicense(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLicense
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLicense(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLicense
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLicense
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLicense
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLicense
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLicense
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLicense        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLicense          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLicense = fmt.Errorf("proto: unexpected end of group")
)
