// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: license/v1/license_type.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// LicenseType defines a template for issuing licenses.
type LicenseType struct {
	// id is the owner-supplied identifier, e.g. "nodelabs.node".
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// transferrable indicates whether holders may transfer this license type.
	Transferrable bool `protobuf:"varint,2,opt,name=transferrable,proto3" json:"transferrable,omitempty"`
	// max_supply is the maximum number of licenses outstanding at once, checked
	// against active_count. Revoking frees a slot, so lifetime issued_count may
	// exceed it. 0 = unlimited.
	MaxSupply cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=max_supply,json=maxSupply,proto3,customtype=cosmossdk.io/math.Int" json:"max_supply"`
	// issued_count tracks the total number of licenses issued (used for ID generation).
	IssuedCount cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=issued_count,json=issuedCount,proto3,customtype=cosmossdk.io/math.Int" json:"issued_count"`
	// active_count tracks the number of currently active licenses.
	ActiveCount cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=active_count,json=activeCount,proto3,customtype=cosmossdk.io/math.Int" json:"active_count"`
	// revoked_count tracks the number of revoked licenses.
	RevokedCount cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=revoked_count,json=revokedCount,proto3,customtype=cosmossdk.io/math.Int" json:"revoked_count"`
}

func (m *LicenseType) Reset()         { *m = LicenseType{} }
func (m *LicenseType) String() string { return proto.CompactTextString(m) }
func (*LicenseType) ProtoMessage()    {}
func (*LicenseType) Descriptor() ([]byte, []int) {
	return fileDescriptor_b7f5f1e2dfc409bf, []int{0}
}
func (m *LicenseType) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LicenseType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LicenseType.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LicenseType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LicenseType.Merge(m, src)
}
func (m *LicenseType) XXX_Size() int {
	return m.Size()
}
func (m *LicenseType) XXX_DiscardUnknown() {
	xxx_messageInfo_LicenseType.DiscardUnknown(m)
}

var xxx_messageInfo_LicenseType proto.InternalMessageInfo

func (m *LicenseType) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LicenseType) GetTransferrable() bool {
	if m != nil {
		return m.Transferrable
	}
	return false
}

func init() {
	proto.RegisterType((*LicenseType)(nil), "license.v1.LicenseType")
}

func init() { proto.RegisterFile("license/v1/license_type.proto", fileDescriptor_b7f5f1e2dfc409bf) }

var fileDescriptor_b7f5f1e2dfc409bf = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0xd2, 0xb1, 0x4a, 0xc3, 0x40,
	0x18, 0x07, 0xf0, 0x5c, 0xab, 0xc5, 0x5e, 0x5b, 0xc1, 0xa0, 0x10, 0x0b, 0xa6, 0x45, 0x1c, 0x8a,
	0xd0, 0x5c, 0x8b, 0x6f, 0x50, 0xa7, 0x8a, 0x20, 0xb4, 0xba, 0xb8, 0x84, 0x4b, 0x72, 0xb6, 0x47,
	0x93, 0xbb, 0x90, 0xbb, 0x84, 0xf6, 0x2d, 0x5c, 0x7c, 0x07, 0x47, 0x07, 0x1f, 0xa2, 0x63, 0x71,
	0x12, 0x87, 0x22, 0xed, 0xe0, 0x6b, 0x48, 0x72, 0xb1, 0xe0, 0x9a, 0x25, 0x7c, 0xdf, 0xff, 0x23,
	0x3f, 0x3e, 0xb8, 0x0f, 0x9e, 0xf9, 0xd4, 0x25, 0x4c, 0x10, 0x94, 0xf4, 0x51, 0x5e, 0xda, 0x72,
	0x11, 0x12, 0x2b, 0x8c, 0xb8, 0xe4, 0x3a, 0xcc, 0x33, 0x2b, 0xe9, 0x37, 0x8f, 0x70, 0x40, 0x19,
	0x47, 0xd9, 0x57, 0x8d, 0x9b, 0xa7, 0x2e, 0x17, 0x01, 0x17, 0x76, 0xd6, 0x21, 0xd5, 0xe4, 0xa3,
	0xe3, 0x09, 0x9f, 0x70, 0x95, 0xa7, 0x95, 0x4a, 0xcf, 0x5f, 0xca, 0xb0, 0x76, 0xab, 0xc8, 0xfb,
	0x45, 0x48, 0xf4, 0x43, 0x58, 0xa2, 0x9e, 0x01, 0xda, 0xa0, 0x53, 0x1d, 0x95, 0xa8, 0xa7, 0x5f,
	0xc0, 0x86, 0x8c, 0x30, 0x13, 0x4f, 0x24, 0x8a, 0xb0, 0xe3, 0x13, 0xa3, 0xd4, 0x06, 0x9d, 0x83,
	0xd1, 0xff, 0x50, 0xbf, 0x83, 0x30, 0xc0, 0x73, 0x5b, 0xc4, 0x61, 0xe8, 0x2f, 0x8c, 0x72, 0xfa,
	0xf7, 0xa0, 0xb7, 0x5c, 0xb7, 0xb4, 0xaf, 0x75, 0xeb, 0x44, 0x6d, 0x21, 0xbc, 0x99, 0x45, 0x39,
	0x0a, 0xb0, 0x9c, 0x5a, 0x43, 0x26, 0x3f, 0xde, 0xbb, 0x30, 0x5f, 0x6f, 0xc8, 0xe4, 0xeb, 0xcf,
	0xdb, 0x25, 0x18, 0x55, 0x03, 0x3c, 0x1f, 0x67, 0x84, 0x3e, 0x86, 0x75, 0x2a, 0x44, 0x4c, 0x3c,
	0xdb, 0xe5, 0x31, 0x93, 0xc6, 0x5e, 0x41, 0xb2, 0xa6, 0x94, 0xeb, 0x14, 0x49, 0x51, 0xec, 0x4a,
	0x9a, 0x90, 0x1c, 0xdd, 0x2f, 0x8a, 0x2a, 0x45, 0xa1, 0x0f, 0xb0, 0x11, 0x91, 0x84, 0xcf, 0x76,
	0xab, 0x56, 0x0a, 0xaa, 0xf5, 0x9c, 0xc9, 0xd8, 0xc1, 0xcd, 0x72, 0x63, 0x82, 0xd5, 0xc6, 0x04,
	0xdf, 0x1b, 0x13, 0x3c, 0x6f, 0x4d, 0x6d, 0xb5, 0x35, 0xb5, 0xcf, 0xad, 0xa9, 0x3d, 0xf6, 0x26,
	0x54, 0x4e, 0x63, 0xc7, 0x72, 0x79, 0x80, 0x18, 0xf7, 0x88, 0x8f, 0x1d, 0xd1, 0x15, 0xde, 0x6c,
	0xd7, 0xa0, 0xf9, 0xdf, 0xe1, 0xa0, 0xf4, 0x70, 0x84, 0x53, 0xc9, 0x9e, 0xfa, 0xea, 0x37, 0x00,
	0x00, 0xff, 0xff, 0xed, 0x25, 0x8f, 0xe3, 0x5b, 0x02, 0x00, 0x00,
}

func (m *LicenseType) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LicenseType) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LicenseType) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.RevokedCount.Size()
		i -= size
		if _, err := m.RevokedCount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLicenseType(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.ActiveCount.Size()
		i -= size
		if _, err := m.ActiveCount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLicenseType(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.IssuedCount.Size()
		i -= size
		if _, err := m.IssuedCount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLicenseType(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.MaxSupply.Size()
		i -= size
		if _, err := m.MaxSupply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLicenseType(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Transferrable {
		i--
		if m.Transferrable {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintLicenseType(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintLicenseType(dAtA []byte, offset int, v uint64) int {
	offset -= sovLicenseType(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LicenseType) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovLicenseType(uint64(l))
	}
	if m.Transferrable {
		n += 2
	}
	l = m.MaxSupply.Size()
	n += 1 + l + sovLicenseType(uint64(l))
	l = m.IssuedCount.Size()
	n += 1 + l + sovLicenseType(uint64(l))
	l = m.ActiveCount.Size()
	n += 1 + l + sovLicenseType(uint64(l))
	l = m.RevokedCount.Size()
	n += 1 + l + sovLicenseType(uint64(l))
	return n
}

func sovLicenseType(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLicenseType(x uint64) (n int) {
	return sovLicenseType(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LicenseType) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLicenseType
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LicenseType: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LicenseType: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicenseType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLicenseType
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLicenseType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Transferrable", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicenseType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Transferrable = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicenseType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLicenseType
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLicenseType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuedCount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicenseType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLicenseType
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLicenseType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.IssuedCount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveCount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicenseType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLicenseType
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLicenseType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ActiveCount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevokedCount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLicenseType
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLicenseType
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLicenseType
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RevokedCount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLicenseType(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLicenseType
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLicenseType(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLicenseType
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLicenseType
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLicenseType
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLicenseType
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLicenseType
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLicenseType
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLicenseType        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLicenseType          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLicenseType = fmt.Errorf("proto: unexpected end of group")
)
