// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: license/v1/query.proto

package licensev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName                  = "/license.v1.Query/Params"
	Query_Actions_FullMethodName                 = "/license.v1.Query/Actions"
	Query_Grants_FullMethodName                  = "/license.v1.Query/Grants"
	Query_GrantsByGrantee_FullMethodName         = "/license.v1.Query/GrantsByGrantee"
	Query_GrantsByScope_FullMethodName           = "/license.v1.Query/GrantsByScope"
	Query_Can_FullMethodName                     = "/license.v1.Query/Can"
	Query_LicenseType_FullMethodName             = "/license.v1.Query/LicenseType"
	Query_LicenseTypes_FullMethodName            = "/license.v1.Query/LicenseTypes"
	Query_License_FullMethodName                 = "/license.v1.Query/License"
	Query_Licenses_FullMethodName                = "/license.v1.Query/Licenses"
	Query_LicensesByType_FullMethodName          = "/license.v1.Query/LicensesByType"
	Query_LicensesByHolder_FullMethodName        = "/license.v1.Query/LicensesByHolder"
	Query_LicensesByHolderAndType_FullMethodName = "/license.v1.Query/LicensesByHolderAndType"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries the module parameters, including the module owner.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Actions queries the action vocabulary this module recognises. It is
	// compiled into the binary rather than stored, so the answer is the same for
	// every node running this version.
	Actions(ctx context.Context, in *QueryActionsRequest, opts ...grpc.CallOption) (*QueryActionsResponse, error)
	// Grants queries every access grant in the module.
	Grants(ctx context.Context, in *QueryGrantsRequest, opts ...grpc.CallOption) (*QueryGrantsResponse, error)
	// GrantsByGrantee queries the grants held by an address.
	GrantsByGrantee(ctx context.Context, in *QueryGrantsByGranteeRequest, opts ...grpc.CallOption) (*QueryGrantsByGranteeResponse, error)
	// GrantsByScope queries the grants that apply to a license type, optionally
	// narrowed to a single action.
	GrantsByScope(ctx context.Context, in *QueryGrantsByScopeRequest, opts ...grpc.CallOption) (*QueryGrantsByScopeResponse, error)
	// Can reports whether a grantee holds an (action, scope) grant.
	Can(ctx context.Context, in *QueryCanRequest, opts ...grpc.CallOption) (*QueryCanResponse, error)
	// LicenseType queries a license type by id.
	LicenseType(ctx context.Context, in *QueryLicenseTypeRequest, opts ...grpc.CallOption) (*QueryLicenseTypeResponse, error)
	// LicenseTypes queries all license types.
	LicenseTypes(ctx context.Context, in *QueryLicenseTypesRequest, opts ...grpc.CallOption) (*QueryLicenseTypesResponse, error)
	// License queries a license by id. Ids are unique chain-wide, so no license
	// type is needed to resolve one.
	License(ctx context.Context, in *QueryLicenseRequest, opts ...grpc.CallOption) (*QueryLicenseResponse, error)
	// Licenses queries all licenses across all license types, active and revoked.
	Licenses(ctx context.Context, in *QueryLicensesRequest, opts ...grpc.CallOption) (*QueryLicensesResponse, error)
	// LicensesByType queries all licenses for a given license type.
	LicensesByType(ctx context.Context, in *QueryLicensesByTypeRequest, opts ...grpc.CallOption) (*QueryLicensesByTypeResponse, error)
	// LicensesByHolder queries the active licenses held by a given address.
	// Revoked licenses are not indexed by holder; use License or LicensesByType
	// to look them up.
	LicensesByHolder(ctx context.Context, in *QueryLicensesByHolderRequest, opts ...grpc.CallOption) (*QueryLicensesByHolderResponse, error)
	// LicensesByHolderAndType queries the active licenses held by a given
	// address for a specific type. Revoked licenses are not indexed by holder;
	// use License or LicensesByType to look them up.
	LicensesByHolderAndType(ctx context.Context, in *QueryLicensesByHolderAndTypeRequest, opts ...grpc.CallOption) (*QueryLicensesByHolderAndTypeResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Actions(ctx context.Context, in *QueryActionsRequest, opts ...grpc.CallOption) (*QueryActionsResponse, error) {
	out := new(QueryActionsResponse)
	err := c.cc.Invoke(ctx, Query_Actions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Grants(ctx context.Context, in *QueryGrantsRequest, opts ...grpc.CallOption) (*QueryGrantsResponse, error) {
	out := new(QueryGrantsResponse)
	err := c.cc.Invoke(ctx, Query_Grants_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GrantsByGrantee(ctx context.Context, in *QueryGrantsByGranteeRequest, opts ...grpc.CallOption) (*QueryGrantsByGranteeResponse, error) {
	out := new(QueryGrantsByGranteeResponse)
	err := c.cc.Invoke(ctx, Query_GrantsByGrantee_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GrantsByScope(ctx context.Context, in *QueryGrantsByScopeRequest, opts ...grpc.CallOption) (*QueryGrantsByScopeResponse, error) {
	out := new(QueryGrantsByScopeResponse)
	err := c.cc.Invoke(ctx, Query_GrantsByScope_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Can(ctx context.Context, in *QueryCanRequest, opts ...grpc.CallOption) (*QueryCanResponse, error) {
	out := new(QueryCanResponse)
	err := c.cc.Invoke(ctx, Query_Can_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LicenseType(ctx context.Context, in *QueryLicenseTypeRequest, opts ...grpc.CallOption) (*QueryLicenseTypeResponse, error) {
	out := new(QueryLicenseTypeResponse)
	err := c.cc.Invoke(ctx, Query_LicenseType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LicenseTypes(ctx context.Context, in *QueryLicenseTypesRequest, opts ...grpc.CallOption) (*QueryLicenseTypesResponse, error) {
	out := new(QueryLicenseTypesResponse)
	err := c.cc.Invoke(ctx, Query_LicenseTypes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) License(ctx context.Context, in *QueryLicenseRequest, opts ...grpc.CallOption) (*QueryLicenseResponse, error) {
	out := new(QueryLicenseResponse)
	err := c.cc.Invoke(ctx, Query_License_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Licenses(ctx context.Context, in *QueryLicensesRequest, opts ...grpc.CallOption) (*QueryLicensesResponse, error) {
	out := new(QueryLicensesResponse)
	err := c.cc.Invoke(ctx, Query_Licenses_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LicensesByType(ctx context.Context, in *QueryLicensesByTypeRequest, opts ...grpc.CallOption) (*QueryLicensesByTypeResponse, error) {
	out := new(QueryLicensesByTypeResponse)
	err := c.cc.Invoke(ctx, Query_LicensesByType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LicensesByHolder(ctx context.Context, in *QueryLicensesByHolderRequest, opts ...grpc.CallOption) (*QueryLicensesByHolderResponse, error) {
	out := new(QueryLicensesByHolderResponse)
	err := c.cc.Invoke(ctx, Query_LicensesByHolder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LicensesByHolderAndType(ctx context.Context, in *QueryLicensesByHolderAndTypeRequest, opts ...grpc.CallOption) (*QueryLicensesByHolderAndTypeResponse, error) {
	out := new(QueryLicensesByHolderAndTypeResponse)
	err := c.cc.Invoke(ctx, Query_LicensesByHolderAndType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Params queries the module parameters, including the module owner.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Actions queries the action vocabulary this module recognises. It is
	// compiled into the binary rather than stored, so the answer is the same for
	// every node running this version.
	Actions(context.Context, *QueryActionsRequest) (*QueryActionsResponse, error)
	// Grants queries every access grant in the module.
	Grants(context.Context, *QueryGrantsRequest) (*QueryGrantsResponse, error)
	// GrantsByGrantee queries the grants held by an address.
	GrantsByGrantee(context.Context, *QueryGrantsByGranteeRequest) (*QueryGrantsByGranteeResponse, error)
	// GrantsByScope queries the grants that apply to a license type, optionally
	// narrowed to a single action.
	GrantsByScope(context.Context, *QueryGrantsByScopeRequest) (*QueryGrantsByScopeResponse, error)
	// Can reports whether a grantee holds an (action, scope) grant.
	Can(context.Context, *QueryCanRequest) (*QueryCanResponse, error)
	// LicenseType queries a license type by id.
	LicenseType(context.Context, *QueryLicenseTypeRequest) (*QueryLicenseTypeResponse, error)
	// LicenseTypes queries all license types.
	LicenseTypes(context.Context, *QueryLicenseTypesRequest) (*QueryLicenseTypesResponse, error)
	// License queries a license by id. Ids are unique chain-wide, so no license
	// type is needed to resolve one.
	License(context.Context, *QueryLicenseRequest) (*QueryLicenseResponse, error)
	// Licenses queries all licenses across all license types, active and revoked.
	Licenses(context.Context, *QueryLicensesRequest) (*QueryLicensesResponse, error)
	// LicensesByType queries all licenses for a given license type.
	LicensesByType(context.Context, *QueryLicensesByTypeRequest) (*QueryLicensesByTypeResponse, error)
	// LicensesByHolder queries the active licenses held by a given address.
	// Revoked licenses are not indexed by holder; use License or LicensesByType
	// to look them up.
	LicensesByHolder(context.Context, *QueryLicensesByHolderRequest) (*QueryLicensesByHolderResponse, error)
	// LicensesByHolderAndType queries the active licenses held by a given
	// address for a specific type. Revoked licenses are not indexed by holder;
	// use License or LicensesByType to look them up.
	LicensesByHolderAndType(context.Context, *QueryLicensesByHolderAndTypeRequest) (*QueryLicensesByHolderAndTypeResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) Actions(context.Context, *QueryActionsRequest) (*QueryActionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Actions not implemented")
}
func (UnimplementedQueryServer) Grants(context.Context, *QueryGrantsRequest) (*QueryGrantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Grants not implemented")
}
func (UnimplementedQueryServer) GrantsByGrantee(context.Context, *QueryGrantsByGranteeRequest) (*QueryGrantsByGranteeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantsByGrantee not implemented")
}
func (UnimplementedQueryServer) GrantsByScope(context.Context, *QueryGrantsByScopeRequest) (*QueryGrantsByScopeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantsByScope not implemented")
}
func (UnimplementedQueryServer) Can(context.Context, *QueryCanRequest) (*QueryCanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Can not implemented")
}
func (UnimplementedQueryServer) LicenseType(context.Context, *QueryLicenseTypeRequest) (*QueryLicenseTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicenseType not implemented")
}
func (UnimplementedQueryServer) LicenseTypes(context.Context, *QueryLicenseTypesRequest) (*QueryLicenseTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicenseTypes not implemented")
}
func (UnimplementedQueryServer) License(context.Context, *QueryLicenseRequest) (*QueryLicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method License not implemented")
}
func (UnimplementedQueryServer) Licenses(context.Context, *QueryLicensesRequest) (*QueryLicensesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Licenses not implemented")
}
func (UnimplementedQueryServer) LicensesByType(context.Context, *QueryLicensesByTypeRequest) (*QueryLicensesByTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicensesByType not implemented")
}
func (UnimplementedQueryServer) LicensesByHolder(context.Context, *QueryLicensesByHolderRequest) (*QueryLicensesByHolderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicensesByHolder not implemented")
}
func (UnimplementedQueryServer) LicensesByHolderAndType(context.Context, *QueryLicensesByHolderAndTypeRequest) (*QueryLicensesByHolderAndTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LicensesByHolderAndType not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Actions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryActionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Actions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Actions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Actions(ctx, req.(*QueryActionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Grants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Grants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Grants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Grants(ctx, req.(*QueryGrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GrantsByGrantee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGrantsByGranteeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GrantsByGrantee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GrantsByGrantee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GrantsByGrantee(ctx, req.(*QueryGrantsByGranteeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GrantsByScope_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGrantsByScopeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GrantsByScope(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_GrantsByScope_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GrantsByScope(ctx, req.(*QueryGrantsByScopeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Can_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Can(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Can_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Can(ctx, req.(*QueryCanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LicenseType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicenseTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LicenseType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LicenseType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LicenseType(ctx, req.(*QueryLicenseTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LicenseTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicenseTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LicenseTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LicenseTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LicenseTypes(ctx, req.(*QueryLicenseTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_License_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).License(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_License_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).License(ctx, req.(*QueryLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Licenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicensesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Licenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Licenses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Licenses(ctx, req.(*QueryLicensesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LicensesByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicensesByTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LicensesByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LicensesByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LicensesByType(ctx, req.(*QueryLicensesByTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LicensesByHolder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicensesByHolderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LicensesByHolder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LicensesByHolder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LicensesByHolder(ctx, req.(*QueryLicensesByHolderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LicensesByHolderAndType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLicensesByHolderAndTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LicensesByHolderAndType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_LicensesByHolderAndType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LicensesByHolderAndType(ctx, req.(*QueryLicensesByHolderAndTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "license.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Actions",
			Handler:    _Query_Actions_Handler,
		},
		{
			MethodName: "Grants",
			Handler:    _Query_Grants_Handler,
		},
		{
			MethodName: "GrantsByGrantee",
			Handler:    _Query_GrantsByGrantee_Handler,
		},
		{
			MethodName: "GrantsByScope",
			Handler:    _Query_GrantsByScope_Handler,
		},
		{
			MethodName: "Can",
			Handler:    _Query_Can_Handler,
		},
		{
			MethodName: "LicenseType",
			Handler:    _Query_LicenseType_Handler,
		},
		{
			MethodName: "LicenseTypes",
			Handler:    _Query_LicenseTypes_Handler,
		},
		{
			MethodName: "License",
			Handler:    _Query_License_Handler,
		},
		{
			MethodName: "Licenses",
			Handler:    _Query_Licenses_Handler,
		},
		{
			MethodName: "LicensesByType",
			Handler:    _Query_LicensesByType_Handler,
		},
		{
			MethodName: "LicensesByHolder",
			Handler:    _Query_LicensesByHolder_Handler,
		},
		{
			MethodName: "LicensesByHolderAndType",
			Handler:    _Query_LicensesByHolderAndType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "license/v1/query.proto",
}
