// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: license/v1/tx.proto

package licensev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_CreateLicenseType_FullMethodName = "/license.v1.Msg/CreateLicenseType"
	Msg_IssueLicenses_FullMethodName     = "/license.v1.Msg/IssueLicenses"
	Msg_RevokeLicenses_FullMethodName    = "/license.v1.Msg/RevokeLicenses"
	Msg_UpdateLicenseType_FullMethodName = "/license.v1.Msg/UpdateLicenseType"
	Msg_UpdateParams_FullMethodName      = "/license.v1.Msg/UpdateParams"
	Msg_TransferOwnership_FullMethodName = "/license.v1.Msg/TransferOwnership"
	Msg_GrantAccess_FullMethodName       = "/license.v1.Msg/GrantAccess"
	Msg_RevokeAccess_FullMethodName      = "/license.v1.Msg/RevokeAccess"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// CreateLicenseType creates a new license type. Signer must hold the
	// module-wide "type.create" grant; owning the module is not sufficient on
	// its own.
	CreateLicenseType(ctx context.Context, in *MsgCreateLicenseType, opts ...grpc.CallOption) (*MsgCreateLicenseTypeResponse, error)
	// IssueLicenses issues one or more licenses. Signer must have the "issue" grant for the license type.
	IssueLicenses(ctx context.Context, in *MsgIssueLicenses, opts ...grpc.CallOption) (*MsgIssueLicensesResponse, error)
	// RevokeLicenses revokes the licenses with the given ids.
	// Signer must have the "revoke" grant for the license type.
	RevokeLicenses(ctx context.Context, in *MsgRevokeLicenses, opts ...grpc.CallOption) (*MsgRevokeLicensesResponse, error)
	// UpdateLicenseType updates an existing license type. Signer must be the module owner.
	UpdateLicenseType(ctx context.Context, in *MsgUpdateLicenseType, opts ...grpc.CallOption) (*MsgUpdateLicenseTypeResponse, error)
	// UpdateParams updates the module parameters, including the module owner.
	// Signer must be the module authority (governance). It is how an owner is
	// first established outside genesis, and how a lost or compromised owner key
	// is recovered without its cooperation.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// TransferOwnership hands the module to a new owner. Signer must be the
	// current owner. It writes only the owner parameter, leaving every other
	// parameter untouched.
	TransferOwnership(ctx context.Context, in *MsgTransferOwnership, opts ...grpc.CallOption) (*MsgTransferOwnershipResponse, error)
	// GrantAccess merges access grants for a grantee. Signer must be the module
	// owner. Existing grants are preserved; new (action, scope) pairs are
	// unioned in.
	GrantAccess(ctx context.Context, in *MsgGrantAccess, opts ...grpc.CallOption) (*MsgGrantAccessResponse, error)
	// RevokeAccess removes the given (action, scope) pairs from a grantee. Pairs
	// that are not currently granted are silently ignored. Signer must be the
	// module owner.
	RevokeAccess(ctx context.Context, in *MsgRevokeAccess, opts ...grpc.CallOption) (*MsgRevokeAccessResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateLicenseType(ctx context.Context, in *MsgCreateLicenseType, opts ...grpc.CallOption) (*MsgCreateLicenseTypeResponse, error) {
	out := new(MsgCreateLicenseTypeResponse)
	err := c.cc.Invoke(ctx, Msg_CreateLicenseType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) IssueLicenses(ctx context.Context, in *MsgIssueLicenses, opts ...grpc.CallOption) (*MsgIssueLicensesResponse, error) {
	out := new(MsgIssueLicensesResponse)
	err := c.cc.Invoke(ctx, Msg_IssueLicenses_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeLicenses(ctx context.Context, in *MsgRevokeLicenses, opts ...grpc.CallOption) (*MsgRevokeLicensesResponse, error) {
	out := new(MsgRevokeLicensesResponse)
	err := c.cc.Invoke(ctx, Msg_RevokeLicenses_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateLicenseType(ctx context.Context, in *MsgUpdateLicenseType, opts ...grpc.CallOption) (*MsgUpdateLicenseTypeResponse, error) {
	out := new(MsgUpdateLicenseTypeResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateLicenseType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferOwnership(ctx context.Context, in *MsgTransferOwnership, opts ...grpc.CallOption) (*MsgTransferOwnershipResponse, error) {
	out := new(MsgTransferOwnershipResponse)
	err := c.cc.Invoke(ctx, Msg_TransferOwnership_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) GrantAccess(ctx context.Context, in *MsgGrantAccess, opts ...grpc.CallOption) (*MsgGrantAccessResponse, error) {
	out := new(MsgGrantAccessResponse)
	err := c.cc.Invoke(ctx, Msg_GrantAccess_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeAccess(ctx context.Context, in *MsgRevokeAccess, opts ...grpc.CallOption) (*MsgRevokeAccessResponse, error) {
	out := new(MsgRevokeAccessResponse)
	err := c.cc.Invoke(ctx, Msg_RevokeAccess_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// CreateLicenseType creates a new license type. Signer must hold the
	// module-wide "type.create" grant; owning the module is not sufficient on
	// its own.
	CreateLicenseType(context.Context, *MsgCreateLicenseType) (*MsgCreateLicenseTypeResponse, error)
	// IssueLicenses issues one or more licenses. Signer must have the "issue" grant for the license type.
	IssueLicenses(context.Context, *MsgIssueLicenses) (*MsgIssueLicensesResponse, error)
	// RevokeLicenses revokes the licenses with the given ids.
	// Signer must have the "revoke" grant for the license type.
	RevokeLicenses(context.Context, *MsgRevokeLicenses) (*MsgRevokeLicensesResponse, error)
	// UpdateLicenseType updates an existing license type. Signer must be the module owner.
	UpdateLicenseType(context.Context, *MsgUpdateLicenseType) (*MsgUpdateLicenseTypeResponse, error)
	// UpdateParams updates the module parameters, including the module owner.
	// Signer must be the module authority (governance). It is how an owner is
	// first established outside genesis, and how a lost or compromised owner key
	// is recovered without its cooperation.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// TransferOwnership hands the module to a new owner. Signer must be the
	// current owner. It writes only the owner parameter, leaving every other
	// parameter untouched.
	TransferOwnership(context.Context, *MsgTransferOwnership) (*MsgTransferOwnershipResponse, error)
	// GrantAccess merges access grants for a grantee. Signer must be the module
	// owner. Existing grants are preserved; new (action, scope) pairs are
	// unioned in.
	GrantAccess(context.Context, *MsgGrantAccess) (*MsgGrantAccessResponse, error)
	// RevokeAccess removes the given (action, scope) pairs from a grantee. Pairs
	// that are not currently granted are silently ignored. Signer must be the
	// module owner.
	RevokeAccess(context.Context, *MsgRevokeAccess) (*MsgRevokeAccessResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) CreateLicenseType(context.Context, *MsgCreateLicenseType) (*MsgCreateLicenseTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLicenseType not implemented")
}
func (UnimplementedMsgServer) IssueLicenses(context.Context, *MsgIssueLicenses) (*MsgIssueLicensesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssueLicenses not implemented")
}
func (UnimplementedMsgServer) RevokeLicenses(context.Context, *MsgRevokeLicenses) (*MsgRevokeLicensesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeLicenses not implemented")
}
func (UnimplementedMsgServer) UpdateLicenseType(context.Context, *MsgUpdateLicenseType) (*MsgUpdateLicenseTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLicenseType not implemented")
}
func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) TransferOwnership(context.Context, *MsgTransferOwnership) (*MsgTransferOwnershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferOwnership not implemented")
}
func (UnimplementedMsgServer) GrantAccess(context.Context, *MsgGrantAccess) (*MsgGrantAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantAccess not implemented")
}
func (UnimplementedMsgServer) RevokeAccess(context.Context, *MsgRevokeAccess) (*MsgRevokeAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeAccess not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_CreateLicenseType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateLicenseType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateLicenseType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateLicenseType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateLicenseType(ctx, req.(*MsgCreateLicenseType))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_IssueLicenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgIssueLicenses)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).IssueLicenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_IssueLicenses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).IssueLicenses(ctx, req.(*MsgIssueLicenses))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeLicenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeLicenses)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeLicenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevokeLicenses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeLicenses(ctx, req.(*MsgRevokeLicenses))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateLicenseType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateLicenseType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateLicenseType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateLicenseType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateLicenseType(ctx, req.(*MsgUpdateLicenseType))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferOwnership)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_TransferOwnership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferOwnership(ctx, req.(*MsgTransferOwnership))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_GrantAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgGrantAccess)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).GrantAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_GrantAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).GrantAccess(ctx, req.(*MsgGrantAccess))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeAccess)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevokeAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeAccess(ctx, req.(*MsgRevokeAccess))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "license.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLicenseType",
			Handler:    _Msg_CreateLicenseType_Handler,
		},
		{
			MethodName: "IssueLicenses",
			Handler:    _Msg_IssueLicenses_Handler,
		},
		{
			MethodName: "RevokeLicenses",
			Handler:    _Msg_RevokeLicenses_Handler,
		},
		{
			MethodName: "UpdateLicenseType",
			Handler:    _Msg_UpdateLicenseType_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "TransferOwnership",
			Handler:    _Msg_TransferOwnership_Handler,
		},
		{
			MethodName: "GrantAccess",
			Handler:    _Msg_GrantAccess_Handler,
		},
		{
			MethodName: "RevokeAccess",
			Handler:    _Msg_RevokeAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "license/v1/tx.proto",
}
