package cli

import (
	"fmt"

	"github.com/cosmos/cosmos-sdk/client"
	"github.com/cosmos/cosmos-sdk/client/flags"
	"github.com/cosmos/cosmos-sdk/client/tx"
	sdk "github.com/cosmos/cosmos-sdk/types"
	"github.com/spf13/cobra"

	accesscli "github.com/nodelabs-sdk/nodelabs/x/access/client/cli"
	"github.com/nodelabs-sdk/nodelabs/x/network/types"
)

// GetTxCmd returns the transaction commands for this module. Only the access
// commands live here; everything else maps cleanly to positional args and is
// generated by autocli.
func GetTxCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:                        types.ModuleName,
		Short:                      fmt.Sprintf("%s transactions subcommands", types.ModuleName),
		DisableFlagParsing:         true,
		SuggestionsMinimumDistance: 2,
		RunE:                       client.ValidateCmd,
	}

	cmd.AddCommand(CmdGrantAccess())
	cmd.AddCommand(CmdRevokeAccess())

	return cmd
}

// CmdGrantAccess returns a command to grant actions to an address.
//
// Usage:
//
//	grant-access [grantee] [actions]
//
// Where [actions] is a comma-delimited list (e.g. "wallet.create"). This
// module does not scope its actions, so no scope argument is taken. The module
// owner is taken from --from.
func CmdGrantAccess() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "grant-access [grantee] [actions]",
		Short: "Grant actions to an address",
		Long: `Grant actions to a given address. The module owner (--from) must sign.

[grantee]  The address receiving the grants.
[actions]  Comma-delimited list of actions to grant. Query the vocabulary with:
           nodelabsd query network actions

This module does not scope its actions, so every grant is module-wide and no
scope argument is taken.

Grants are MERGED with any existing grants for the grantee — previously granted
actions are preserved. To remove actions, use revoke-access.

Example:
  nodelabsd tx network grant-access nodelabs1abc... wallet.create,nodetype.create \
    --from owner --gas auto --gas-adjustment 1.5 --fees 100000aatom -y`,
		Args: cobra.ExactArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			clientCtx, err := client.GetClientTxContext(cmd)
			if err != nil {
				return err
			}

			grantee := args[0]
			if _, err := sdk.AccAddressFromBech32(grantee); err != nil {
				return fmt.Errorf("invalid grantee address %q: %w", grantee, err)
			}

			// The module is unscoped throughout, so the scopes argument is
			// fixed rather than exposed: a non-empty scope is rejected on
			// chain, and offering the flag would only invite that error.
			entries, err := accesscli.ParseGrantEntries(args[1], accesscli.ModuleWideScopes)
			if err != nil {
				return err
			}

			msg := &types.MsgGrantAccess{
				Owner:   clientCtx.GetFromAddress().String(),
				Grantee: grantee,
				Grants:  entries,
			}

			return tx.GenerateOrBroadcastTxCLI(clientCtx, cmd.Flags(), msg)
		},
	}

	flags.AddTxFlagsToCmd(cmd)
	return cmd
}

// CmdRevokeAccess returns a command to remove actions from a grantee.
//
// Usage:
//
//	revoke-access [grantee] [action1] [action2] ...
//
// Actions that aren't currently granted are silently ignored. The module owner
// is taken from --from.
func CmdRevokeAccess() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "revoke-access [grantee] [action ...]",
		Short: "Revoke actions from a grantee",
		Long: `Revoke actions from an address. The module owner (--from) must sign.

This module does not scope its actions, so each argument after the grantee is a
bare action name.

Actions that aren't currently granted are silently ignored.

Example:
  nodelabsd tx network revoke-access nodelabs1abc... wallet.create \
    --from owner --gas auto --fees 100000aatom -y`,
		Args: cobra.MinimumNArgs(2),
		RunE: func(cmd *cobra.Command, args []string) error {
			clientCtx, err := client.GetClientTxContext(cmd)
			if err != nil {
				return err
			}

			grantee := args[0]
			if _, err := sdk.AccAddressFromBech32(grantee); err != nil {
				return fmt.Errorf("invalid grantee address %q: %w", grantee, err)
			}

			pairs, err := accesscli.ParseRevokePairs(args[1:])
			if err != nil {
				return err
			}
			// A scope here could only ever miss: grants are filed under the
			// empty scope, so reject it rather than silently no-op.
			for i, p := range pairs {
				if p.Scope != "" {
					return fmt.Errorf("action %d: %q is module-wide, so it takes no scope (got %q)", i, p.Action, p.Scope)
				}
			}

			msg := &types.MsgRevokeAccess{
				Owner:   clientCtx.GetFromAddress().String(),
				Grantee: grantee,
				Actions: pairs,
			}

			return tx.GenerateOrBroadcastTxCLI(clientCtx, cmd.Flags(), msg)
		},
	}

	flags.AddTxFlagsToCmd(cmd)
	return cmd
}
