// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: network/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/nodelabs-sdk/nodelabs/x/access/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// NodeStatusCounter pairs a node address with its daily status-update
// counter for genesis import/export.
type NodeStatusCounter struct {
	// node_address is the node the counter belongs to.
	NodeAddress string `protobuf:"bytes,1,opt,name=node_address,json=nodeAddress,proto3" json:"node_address,omitempty"`
	// counter is the node's rolling daily status-update counter.
	Counter ActivityCounter `protobuf:"bytes,2,opt,name=counter,proto3" json:"counter"`
}

func (m *NodeStatusCounter) Reset()         { *m = NodeStatusCounter{} }
func (m *NodeStatusCounter) String() string { return proto.CompactTextString(m) }
func (*NodeStatusCounter) ProtoMessage()    {}
func (*NodeStatusCounter) Descriptor() ([]byte, []int) {
	return fileDescriptor_203602c3918c6872, []int{0}
}
func (m *NodeStatusCounter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeStatusCounter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NodeStatusCounter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NodeStatusCounter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatusCounter.Merge(m, src)
}
func (m *NodeStatusCounter) XXX_Size() int {
	return m.Size()
}
func (m *NodeStatusCounter) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatusCounter.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatusCounter proto.InternalMessageInfo

func (m *NodeStatusCounter) GetNodeAddress() string {
	if m != nil {
		return m.NodeAddress
	}
	return ""
}

func (m *NodeStatusCounter) GetCounter() ActivityCounter {
	if m != nil {
		return m.Counter
	}
	return ActivityCounter{}
}

// GaslessCounter is one gasless-admission daily counter for genesis
// import/export, keyed by counter kind, signer address, and scope.
type GaslessCounter struct {
	// kind is the admission counter kind ("authorize", "activate",
	// "deactivate").
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// signer is the address the counter is keyed on.
	Signer string `protobuf:"bytes,2,opt,name=signer,proto3" json:"signer,omitempty"`
	// scope narrows the counter within (kind, signer). It is the node type for
	// the "activate" kind, whose ceiling is derived from the licenses backing
	// that node type, and empty for kinds whose limit is a flat param and so
	// has nothing to be scoped by.
	Scope string `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	// counter is the rolling daily counter.
	Counter ActivityCounter `protobuf:"bytes,4,opt,name=counter,proto3" json:"counter"`
}

func (m *GaslessCounter) Reset()         { *m = GaslessCounter{} }
func (m *GaslessCounter) String() string { return proto.CompactTextString(m) }
func (*GaslessCounter) ProtoMessage()    {}
func (*GaslessCounter) Descriptor() ([]byte, []int) {
	return fileDescriptor_203602c3918c6872, []int{1}
}
func (m *GaslessCounter) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GaslessCounter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GaslessCounter.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GaslessCounter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GaslessCounter.Merge(m, src)
}
func (m *GaslessCounter) XXX_Size() int {
	return m.Size()
}
func (m *GaslessCounter) XXX_DiscardUnknown() {
	xxx_messageInfo_GaslessCounter.DiscardUnknown(m)
}

var xxx_messageInfo_GaslessCounter proto.InternalMessageInfo

func (m *GaslessCounter) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *GaslessCounter) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *GaslessCounter) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

func (m *GaslessCounter) GetCounter() ActivityCounter {
	if m != nil {
		return m.Counter
	}
	return ActivityCounter{}
}

// GenesisState defines the network module's genesis state. The denormalized
// structures (operator set, operator-node index, per-operator node counts,
// and the recent-activity index) are derived from nodes and activation_keys
// on import rather than exported, so they can never disagree with the
// primary records.
type GenesisState struct {
	// params are the module parameters.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// nodes are all node records, active and deactivated.
	Nodes []Node `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes"`
	// activation_keys are all activation key records, active and disabled.
	ActivationKeys []ActivationKey `protobuf:"bytes,3,rep,name=activation_keys,json=activationKeys,proto3" json:"activation_keys"`
	// node_status_counters are the per-node daily status-update counters.
	NodeStatusCounters []NodeStatusCounter `protobuf:"bytes,4,rep,name=node_status_counters,json=nodeStatusCounters,proto3" json:"node_status_counters"`
	// gasless_counters are the ante-admission daily counters, exported so an
	// export/import does not reset gasless quotas.
	GaslessCounters []GaslessCounter `protobuf:"bytes,5,rep,name=gasless_counters,json=gaslessCounters,proto3" json:"gasless_counters"`
	// node_types are the registered node types. Every node's type must name one
	// of these; the license-type binding cannot be checked here, because that
	// record lives in x/license.
	NodeTypes []NodeType `protobuf:"bytes,6,rep,name=node_types,json=nodeTypes,proto3" json:"node_types"`
	// grants are the access grants held within this module. This module does not
	// scope its actions, so every grant carries the empty scope.
	Grants []types.Grant `protobuf:"bytes,7,rep,name=grants,proto3" json:"grants"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_203602c3918c6872, []int{2}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetNodes() []Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *GenesisState) GetActivationKeys() []ActivationKey {
	if m != nil {
		return m.ActivationKeys
	}
	return nil
}

func (m *GenesisState) GetNodeStatusCounters() []NodeStatusCounter {
	if m != nil {
		return m.NodeStatusCounters
	}
	return nil
}

func (m *GenesisState) GetGaslessCounters() []GaslessCounter {
	if m != nil {
		return m.GaslessCounters
	}
	return nil
}

func (m *GenesisState) GetNodeTypes() []NodeType {
	if m != nil {
		return m.NodeTypes
	}
	return nil
}

func (m *GenesisState) GetGrants() []types.Grant {
	if m != nil {
		return m.Grants
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeStatusCounter)(nil), "network.v1.NodeStatusCounter")
	proto.RegisterType((*GaslessCounter)(nil), "network.v1.GaslessCounter")
	proto.RegisterType((*GenesisState)(nil), "network.v1.GenesisState")
}

func init() { proto.RegisterFile("network/v1/genesis.proto", fileDescriptor_203602c3918c6872) }

var fileDescriptor_203602c3918c6872 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe3, 0x26, 0x71, 0x95, 0x49, 0xd5, 0x96, 0x55, 0x54, 0x2d, 0x41, 0x98, 0xd0, 0x53,
	0x0e, 0x60, 0xb7, 0xe1, 0x84, 0x38, 0xb5, 0x1c, 0x8a, 0xa8, 0x84, 0x50, 0x80, 0x0b, 0x97, 0x68,
	0x63, 0xaf, 0x8c, 0xe5, 0x76, 0xd7, 0xf2, 0x6c, 0x02, 0x7e, 0x0a, 0x78, 0x2b, 0x7a, 0xec, 0x91,
	0x13, 0x42, 0xc9, 0x8b, 0xa0, 0xfd, 0xe3, 0xd6, 0x09, 0x27, 0x6e, 0x3b, 0x33, 0xdf, 0xfe, 0xe6,
	0xf3, 0x8c, 0x17, 0xa8, 0xe0, 0xea, 0xab, 0x2c, 0xf3, 0x68, 0x79, 0x1a, 0xa5, 0x5c, 0x70, 0xcc,
	0x30, 0x2c, 0x4a, 0xa9, 0x24, 0x01, 0x57, 0x09, 0x97, 0xa7, 0xc3, 0x23, 0x16, 0xc7, 0x1c, 0x51,
	0x8b, 0xec, 0xc9, 0x6a, 0x86, 0x83, 0x54, 0xa6, 0xd2, 0x1c, 0x23, 0x7d, 0x72, 0xd9, 0x26, 0xb3,
	0x86, 0x98, 0xca, 0x31, 0xc2, 0x83, 0x77, 0x32, 0xe1, 0x1f, 0x14, 0x53, 0x0b, 0x7c, 0x2d, 0x17,
	0x42, 0xf1, 0x92, 0x3c, 0x85, 0x3d, 0x21, 0x13, 0x3e, 0x63, 0x49, 0x52, 0x72, 0x44, 0xea, 0x8d,
	0xbc, 0x71, 0x6f, 0xda, 0xd7, 0xb9, 0x33, 0x9b, 0x22, 0xaf, 0x60, 0x37, 0xb6, 0x6a, 0xba, 0x33,
	0xf2, 0xc6, 0xfd, 0xc9, 0xa3, 0xf0, 0xde, 0x5d, 0x78, 0x16, 0xab, 0x6c, 0x99, 0xa9, 0xca, 0x01,
	0xcf, 0x3b, 0x37, 0xbf, 0x9f, 0xb4, 0xa6, 0xf5, 0x8d, 0xe3, 0xef, 0x1e, 0xec, 0x5f, 0x30, 0xbc,
	0xe2, 0x78, 0xd7, 0x92, 0x40, 0x27, 0xcf, 0x44, 0xe2, 0x5a, 0x99, 0x33, 0x39, 0x02, 0x1f, 0xb3,
	0x54, 0xb8, 0x16, 0xbd, 0xa9, 0x8b, 0xc8, 0x00, 0xba, 0x18, 0xcb, 0x82, 0xd3, 0xb6, 0x49, 0xdb,
	0xa0, 0xe9, 0xa8, 0xf3, 0xdf, 0x8e, 0x7e, 0xb6, 0x61, 0xef, 0xc2, 0x0e, 0x5b, 0x8f, 0x82, 0x93,
	0x13, 0xf0, 0x0b, 0x56, 0xb2, 0x6b, 0xfb, 0xf1, 0xfd, 0x09, 0x69, 0xc2, 0xde, 0x9b, 0x8a, 0x63,
	0x38, 0x1d, 0x79, 0x06, 0x5d, 0x3d, 0x20, 0xa4, 0x3b, 0xa3, 0xf6, 0xb8, 0x3f, 0x39, 0x6c, 0x5e,
	0xd0, 0x23, 0x76, 0x72, 0x2b, 0x22, 0x6f, 0xe0, 0x80, 0x69, 0x4b, 0x4c, 0x65, 0x52, 0xcc, 0x72,
	0x5e, 0x21, 0x6d, 0x9b, 0x7b, 0x0f, 0xff, 0x71, 0x6d, 0x24, 0x97, 0xbc, 0x72, 0x80, 0x7d, 0xd6,
	0x4c, 0x22, 0xf9, 0x04, 0x03, 0xb3, 0x2c, 0x34, 0x2b, 0x9c, 0xb9, 0x2f, 0x42, 0xda, 0x31, 0xb8,
	0xc7, 0xdb, 0x36, 0x36, 0x36, 0xed, 0x90, 0x44, 0x6c, 0x17, 0x90, 0x5c, 0xc2, 0x61, 0x6a, 0x57,
	0x74, 0x8f, 0xec, 0x1a, 0xe4, 0xb0, 0x89, 0xdc, 0x5c, 0xa3, 0xe3, 0x1d, 0xa4, 0x1b, 0x59, 0x24,
	0x2f, 0x01, 0x8c, 0x47, 0x55, 0x15, 0x1c, 0xa9, 0x6f, 0x30, 0x83, 0x6d, 0x67, 0x1f, 0xab, 0xa2,
	0x1e, 0x52, 0x4f, 0xb8, 0x18, 0x49, 0x08, 0x7e, 0x5a, 0x32, 0xa1, 0x90, 0xee, 0xba, 0xb9, 0xba,
	0xff, 0x5d, 0x37, 0xd7, 0x85, 0x7a, 0x0d, 0x56, 0x75, 0xfe, 0xf6, 0x66, 0x15, 0x78, 0xb7, 0xab,
	0xc0, 0xfb, 0xb3, 0x0a, 0xbc, 0x1f, 0xeb, 0xa0, 0x75, 0xbb, 0x0e, 0x5a, 0xbf, 0xd6, 0x41, 0xeb,
	0xf3, 0x49, 0x9a, 0xa9, 0x2f, 0x8b, 0x79, 0x18, 0xcb, 0xeb, 0x48, 0xf3, 0xaf, 0xd8, 0x1c, 0x9f,
	0x63, 0x92, 0xdf, 0x05, 0xd1, 0xb7, 0xfa, 0x71, 0x44, 0xc6, 0xe8, 0xdc, 0x37, 0x6f, 0xe4, 0xc5,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x58, 0x18, 0x63, 0x17, 0x93, 0x03, 0x00, 0x00,
}

func (m *NodeStatusCounter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeStatusCounter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeStatusCounter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Counter.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.NodeAddress) > 0 {
		i -= len(m.NodeAddress)
		copy(dAtA[i:], m.NodeAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.NodeAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GaslessCounter) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GaslessCounter) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GaslessCounter) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Counter.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Scope) > 0 {
		i -= len(m.Scope)
		copy(dAtA[i:], m.Scope)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Scope)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Kind) > 0 {
		i -= len(m.Kind)
		copy(dAtA[i:], m.Kind)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Kind)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Grants) > 0 {
		for iNdEx := len(m.Grants) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Grants[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.NodeTypes) > 0 {
		for iNdEx := len(m.NodeTypes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NodeTypes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.GaslessCounters) > 0 {
		for iNdEx := len(m.GaslessCounters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GaslessCounters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.NodeStatusCounters) > 0 {
		for iNdEx := len(m.NodeStatusCounters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NodeStatusCounters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.ActivationKeys) > 0 {
		for iNdEx := len(m.ActivationKeys) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ActivationKeys[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Nodes) > 0 {
		for iNdEx := len(m.Nodes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Nodes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NodeStatusCounter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.NodeAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Counter.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *GaslessCounter) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Kind)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Scope)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Counter.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.Nodes) > 0 {
		for _, e := range m.Nodes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ActivationKeys) > 0 {
		for _, e := range m.ActivationKeys {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.NodeStatusCounters) > 0 {
		for _, e := range m.NodeStatusCounters {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.GaslessCounters) > 0 {
		for _, e := range m.GaslessCounters {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.NodeTypes) > 0 {
		for _, e := range m.NodeTypes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Grants) > 0 {
		for _, e := range m.Grants {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NodeStatusCounter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeStatusCounter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeStatusCounter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Counter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Counter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GaslessCounter) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GaslessCounter: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GaslessCounter: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Kind = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scope", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Scope = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Counter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Counter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nodes = append(m.Nodes, Node{})
			if err := m.Nodes[len(m.Nodes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActivationKeys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ActivationKeys = append(m.ActivationKeys, ActivationKey{})
			if err := m.ActivationKeys[len(m.ActivationKeys)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeStatusCounters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeStatusCounters = append(m.NodeStatusCounters, NodeStatusCounter{})
			if err := m.NodeStatusCounters[len(m.NodeStatusCounters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GaslessCounters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GaslessCounters = append(m.GaslessCounters, GaslessCounter{})
			if err := m.GaslessCounters[len(m.GaslessCounters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeTypes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeTypes = append(m.NodeTypes, NodeType{})
			if err := m.NodeTypes[len(m.NodeTypes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Grants", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Grants = append(m.Grants, types.Grant{})
			if err := m.Grants[len(m.Grants)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
