// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: network/v1/tx.proto

package networkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_CreateOperatorAccount_FullMethodName    = "/network.v1.Msg/CreateOperatorAccount"
	Msg_CreateNodeType_FullMethodName           = "/network.v1.Msg/CreateNodeType"
	Msg_AuthorizeActivationKey_FullMethodName   = "/network.v1.Msg/AuthorizeActivationKey"
	Msg_DeauthorizeActivationKey_FullMethodName = "/network.v1.Msg/DeauthorizeActivationKey"
	Msg_ActivateNode_FullMethodName             = "/network.v1.Msg/ActivateNode"
	Msg_DeactivateNode_FullMethodName           = "/network.v1.Msg/DeactivateNode"
	Msg_UpdateNodeStatus_FullMethodName         = "/network.v1.Msg/UpdateNodeStatus"
	Msg_UpdateParams_FullMethodName             = "/network.v1.Msg/UpdateParams"
	Msg_TransferOwnership_FullMethodName        = "/network.v1.Msg/TransferOwnership"
	Msg_GrantAccess_FullMethodName              = "/network.v1.Msg/GrantAccess"
	Msg_RevokeAccess_FullMethodName             = "/network.v1.Msg/RevokeAccess"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// CreateOperatorAccount creates an on-chain account for an operator wallet.
	// Signer must hold this module's "wallet.create" grant. Fallback for wallets
	// that predate account creation on license issuance or hold no licenses yet.
	CreateOperatorAccount(ctx context.Context, in *MsgCreateOperatorAccount, opts ...grpc.CallOption) (*MsgCreateOperatorAccountResponse, error)
	// CreateNodeType registers a node type bound to a license type. Signer must
	// hold this module's "nodetype.create" grant, and the named license type
	// must exist. Regular gas tx.
	CreateNodeType(ctx context.Context, in *MsgCreateNodeType, opts ...grpc.CallOption) (*MsgCreateNodeTypeResponse, error)
	// AuthorizeActivationKey authorizes a new activation key for the signing
	// operator wallet. Gasless.
	AuthorizeActivationKey(ctx context.Context, in *MsgAuthorizeActivationKey, opts ...grpc.CallOption) (*MsgAuthorizeActivationKeyResponse, error)
	// DeauthorizeActivationKey disables an activation key. Regular gas tx; the
	// handler additionally charges the deauthorize_fee param to the operator.
	DeauthorizeActivationKey(ctx context.Context, in *MsgDeauthorizeActivationKey, opts ...grpc.CallOption) (*MsgDeauthorizeActivationKeyResponse, error)
	// ActivateNode activates a node under an operator, signed by an authorized
	// activation key. Gasless.
	ActivateNode(ctx context.Context, in *MsgActivateNode, opts ...grpc.CallOption) (*MsgActivateNodeResponse, error)
	// DeactivateNode deactivates a node. Signed by the operator, the node's
	// original (still-active) activation key, or the node itself. Gasless.
	DeactivateNode(ctx context.Context, in *MsgDeactivateNode, opts ...grpc.CallOption) (*MsgDeactivateNodeResponse, error)
	// UpdateNodeStatus records a node's periodic status heartbeat. Gasless,
	// limited to status_daily_limit per node per UTC day. The payload is
	// emitted as an event and not stored in state.
	UpdateNodeStatus(ctx context.Context, in *MsgUpdateNodeStatus, opts ...grpc.CallOption) (*MsgUpdateNodeStatusResponse, error)
	// UpdateParams updates the module parameters, including the module owner.
	// Signer must be the module authority (governance). It is how an owner is
	// first established outside genesis, and how a lost or compromised owner key
	// is recovered without its cooperation.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// TransferOwnership hands the module to a new owner. Signer must be the
	// current owner. It writes only the owner parameter, leaving every other
	// parameter untouched.
	TransferOwnership(ctx context.Context, in *MsgTransferOwnership, opts ...grpc.CallOption) (*MsgTransferOwnershipResponse, error)
	// GrantAccess merges access grants for a grantee. Signer must be the module
	// owner. Existing grants are preserved; new actions are unioned in.
	GrantAccess(ctx context.Context, in *MsgGrantAccess, opts ...grpc.CallOption) (*MsgGrantAccessResponse, error)
	// RevokeAccess removes the given actions from a grantee. Actions that are
	// not currently granted are silently ignored. Signer must be the module
	// owner.
	RevokeAccess(ctx context.Context, in *MsgRevokeAccess, opts ...grpc.CallOption) (*MsgRevokeAccessResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateOperatorAccount(ctx context.Context, in *MsgCreateOperatorAccount, opts ...grpc.CallOption) (*MsgCreateOperatorAccountResponse, error) {
	out := new(MsgCreateOperatorAccountResponse)
	err := c.cc.Invoke(ctx, Msg_CreateOperatorAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateNodeType(ctx context.Context, in *MsgCreateNodeType, opts ...grpc.CallOption) (*MsgCreateNodeTypeResponse, error) {
	out := new(MsgCreateNodeTypeResponse)
	err := c.cc.Invoke(ctx, Msg_CreateNodeType_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AuthorizeActivationKey(ctx context.Context, in *MsgAuthorizeActivationKey, opts ...grpc.CallOption) (*MsgAuthorizeActivationKeyResponse, error) {
	out := new(MsgAuthorizeActivationKeyResponse)
	err := c.cc.Invoke(ctx, Msg_AuthorizeActivationKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeauthorizeActivationKey(ctx context.Context, in *MsgDeauthorizeActivationKey, opts ...grpc.CallOption) (*MsgDeauthorizeActivationKeyResponse, error) {
	out := new(MsgDeauthorizeActivationKeyResponse)
	err := c.cc.Invoke(ctx, Msg_DeauthorizeActivationKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ActivateNode(ctx context.Context, in *MsgActivateNode, opts ...grpc.CallOption) (*MsgActivateNodeResponse, error) {
	out := new(MsgActivateNodeResponse)
	err := c.cc.Invoke(ctx, Msg_ActivateNode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeactivateNode(ctx context.Context, in *MsgDeactivateNode, opts ...grpc.CallOption) (*MsgDeactivateNodeResponse, error) {
	out := new(MsgDeactivateNodeResponse)
	err := c.cc.Invoke(ctx, Msg_DeactivateNode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateNodeStatus(ctx context.Context, in *MsgUpdateNodeStatus, opts ...grpc.CallOption) (*MsgUpdateNodeStatusResponse, error) {
	out := new(MsgUpdateNodeStatusResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateNodeStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferOwnership(ctx context.Context, in *MsgTransferOwnership, opts ...grpc.CallOption) (*MsgTransferOwnershipResponse, error) {
	out := new(MsgTransferOwnershipResponse)
	err := c.cc.Invoke(ctx, Msg_TransferOwnership_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) GrantAccess(ctx context.Context, in *MsgGrantAccess, opts ...grpc.CallOption) (*MsgGrantAccessResponse, error) {
	out := new(MsgGrantAccessResponse)
	err := c.cc.Invoke(ctx, Msg_GrantAccess_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RevokeAccess(ctx context.Context, in *MsgRevokeAccess, opts ...grpc.CallOption) (*MsgRevokeAccessResponse, error) {
	out := new(MsgRevokeAccessResponse)
	err := c.cc.Invoke(ctx, Msg_RevokeAccess_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// CreateOperatorAccount creates an on-chain account for an operator wallet.
	// Signer must hold this module's "wallet.create" grant. Fallback for wallets
	// that predate account creation on license issuance or hold no licenses yet.
	CreateOperatorAccount(context.Context, *MsgCreateOperatorAccount) (*MsgCreateOperatorAccountResponse, error)
	// CreateNodeType registers a node type bound to a license type. Signer must
	// hold this module's "nodetype.create" grant, and the named license type
	// must exist. Regular gas tx.
	CreateNodeType(context.Context, *MsgCreateNodeType) (*MsgCreateNodeTypeResponse, error)
	// AuthorizeActivationKey authorizes a new activation key for the signing
	// operator wallet. Gasless.
	AuthorizeActivationKey(context.Context, *MsgAuthorizeActivationKey) (*MsgAuthorizeActivationKeyResponse, error)
	// DeauthorizeActivationKey disables an activation key. Regular gas tx; the
	// handler additionally charges the deauthorize_fee param to the operator.
	DeauthorizeActivationKey(context.Context, *MsgDeauthorizeActivationKey) (*MsgDeauthorizeActivationKeyResponse, error)
	// ActivateNode activates a node under an operator, signed by an authorized
	// activation key. Gasless.
	ActivateNode(context.Context, *MsgActivateNode) (*MsgActivateNodeResponse, error)
	// DeactivateNode deactivates a node. Signed by the operator, the node's
	// original (still-active) activation key, or the node itself. Gasless.
	DeactivateNode(context.Context, *MsgDeactivateNode) (*MsgDeactivateNodeResponse, error)
	// UpdateNodeStatus records a node's periodic status heartbeat. Gasless,
	// limited to status_daily_limit per node per UTC day. The payload is
	// emitted as an event and not stored in state.
	UpdateNodeStatus(context.Context, *MsgUpdateNodeStatus) (*MsgUpdateNodeStatusResponse, error)
	// UpdateParams updates the module parameters, including the module owner.
	// Signer must be the module authority (governance). It is how an owner is
	// first established outside genesis, and how a lost or compromised owner key
	// is recovered without its cooperation.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// TransferOwnership hands the module to a new owner. Signer must be the
	// current owner. It writes only the owner parameter, leaving every other
	// parameter untouched.
	TransferOwnership(context.Context, *MsgTransferOwnership) (*MsgTransferOwnershipResponse, error)
	// GrantAccess merges access grants for a grantee. Signer must be the module
	// owner. Existing grants are preserved; new actions are unioned in.
	GrantAccess(context.Context, *MsgGrantAccess) (*MsgGrantAccessResponse, error)
	// RevokeAccess removes the given actions from a grantee. Actions that are
	// not currently granted are silently ignored. Signer must be the module
	// owner.
	RevokeAccess(context.Context, *MsgRevokeAccess) (*MsgRevokeAccessResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) CreateOperatorAccount(context.Context, *MsgCreateOperatorAccount) (*MsgCreateOperatorAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOperatorAccount not implemented")
}
func (UnimplementedMsgServer) CreateNodeType(context.Context, *MsgCreateNodeType) (*MsgCreateNodeTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNodeType not implemented")
}
func (UnimplementedMsgServer) AuthorizeActivationKey(context.Context, *MsgAuthorizeActivationKey) (*MsgAuthorizeActivationKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeActivationKey not implemented")
}
func (UnimplementedMsgServer) DeauthorizeActivationKey(context.Context, *MsgDeauthorizeActivationKey) (*MsgDeauthorizeActivationKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeauthorizeActivationKey not implemented")
}
func (UnimplementedMsgServer) ActivateNode(context.Context, *MsgActivateNode) (*MsgActivateNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateNode not implemented")
}
func (UnimplementedMsgServer) DeactivateNode(context.Context, *MsgDeactivateNode) (*MsgDeactivateNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateNode not implemented")
}
func (UnimplementedMsgServer) UpdateNodeStatus(context.Context, *MsgUpdateNodeStatus) (*MsgUpdateNodeStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNodeStatus not implemented")
}
func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) TransferOwnership(context.Context, *MsgTransferOwnership) (*MsgTransferOwnershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferOwnership not implemented")
}
func (UnimplementedMsgServer) GrantAccess(context.Context, *MsgGrantAccess) (*MsgGrantAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GrantAccess not implemented")
}
func (UnimplementedMsgServer) RevokeAccess(context.Context, *MsgRevokeAccess) (*MsgRevokeAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeAccess not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_CreateOperatorAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateOperatorAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateOperatorAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateOperatorAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateOperatorAccount(ctx, req.(*MsgCreateOperatorAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateNodeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateNodeType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateNodeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_CreateNodeType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateNodeType(ctx, req.(*MsgCreateNodeType))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AuthorizeActivationKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAuthorizeActivationKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AuthorizeActivationKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_AuthorizeActivationKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AuthorizeActivationKey(ctx, req.(*MsgAuthorizeActivationKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeauthorizeActivationKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeauthorizeActivationKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeauthorizeActivationKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DeauthorizeActivationKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeauthorizeActivationKey(ctx, req.(*MsgDeauthorizeActivationKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ActivateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgActivateNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ActivateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_ActivateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ActivateNode(ctx, req.(*MsgActivateNode))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeactivateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeactivateNode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeactivateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_DeactivateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeactivateNode(ctx, req.(*MsgDeactivateNode))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateNodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateNodeStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateNodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateNodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateNodeStatus(ctx, req.(*MsgUpdateNodeStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferOwnership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferOwnership)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferOwnership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_TransferOwnership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferOwnership(ctx, req.(*MsgTransferOwnership))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_GrantAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgGrantAccess)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).GrantAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_GrantAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).GrantAccess(ctx, req.(*MsgGrantAccess))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RevokeAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRevokeAccess)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RevokeAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RevokeAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RevokeAccess(ctx, req.(*MsgRevokeAccess))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "network.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOperatorAccount",
			Handler:    _Msg_CreateOperatorAccount_Handler,
		},
		{
			MethodName: "CreateNodeType",
			Handler:    _Msg_CreateNodeType_Handler,
		},
		{
			MethodName: "AuthorizeActivationKey",
			Handler:    _Msg_AuthorizeActivationKey_Handler,
		},
		{
			MethodName: "DeauthorizeActivationKey",
			Handler:    _Msg_DeauthorizeActivationKey_Handler,
		},
		{
			MethodName: "ActivateNode",
			Handler:    _Msg_ActivateNode_Handler,
		},
		{
			MethodName: "DeactivateNode",
			Handler:    _Msg_DeactivateNode_Handler,
		},
		{
			MethodName: "UpdateNodeStatus",
			Handler:    _Msg_UpdateNodeStatus_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "TransferOwnership",
			Handler:    _Msg_TransferOwnership_Handler,
		},
		{
			MethodName: "GrantAccess",
			Handler:    _Msg_GrantAccess_Handler,
		},
		{
			MethodName: "RevokeAccess",
			Handler:    _Msg_RevokeAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network/v1/tx.proto",
}
